In [2]:
import pandas as pd

In [3]:
merged_1 = pd.read_csv('../US_Datasets/merged_us.csv')
merged_1

quarter  gdp_percentage_change_prev_q  fed_fund_rate  \
0   Q1-2001                           1.3       5.597000   
1   Q2-2001                           5.0       4.326703   
2   Q3-2001                           0.0       3.501522   
3   Q4-2001                           2.4       2.130435   
4   Q1-2002                           4.7       1.732889   
..      ...                           ...            ...   
87  Q4-2022                           7.2       3.653370   
88  Q1-2023                           6.6       4.514556   
89  Q2-2023                           4.3       4.988132   
90  Q3-2023                           7.7       5.259239   
91  Q4-2023                           4.8       5.330000   

    gov_effectiveness_perc_rank  PCECTPI  quarterly_fed_balance Bond Rating  \
0                     89.729729   75.012           -7483.666667          AA   
1                     89.729729   75.363           64579.666667           A   
2                     89.729729   75.401          -13889.666667           A   
3                     89.729729   75.432          -11785.333333           A   
4                     89.729729   75.584          -32188.333333           A   
..                          ...      ...                    ...         ...   
87                    87.264153  118.172         -140444.484514         BBB   
88                    87.735847  119.320         -226431.310502         BBB   
89                    87.735847  120.182          -97311.953949         AAA   
90                    87.735847  120.983         -100836.241845         AAA   
91                    87.735847  121.480         -169980.322779         AAA   

    political_stability_perc_rank  producer_price  tax_rev_perc_gdp  \
0                       53.968254      137.766667         11.857705   
1                       53.968254      136.233333         11.857705   
2                       53.968254      133.366667         11.857705   
3                       53.968254      129.400000         11.857705   
4                       53.968254      128.900000          9.868017   
..                            ...             ...               ...   
87                      46.226414      262.038333         12.054833   
88                      47.393364      258.652667         10.223807   
89                      47.393364      254.812667         10.223807   
90                      47.393364      256.816333         10.223807   
91                      47.393364      252.638000         10.223807   

    employment_cost  unemployment_rate  federal_debt_FED_perc_gdp  \
0              84.7           4.233333                    5.00371   
1              85.5           4.400000                    5.04859   
2              86.4           4.833333                    5.03962   
3              87.2           5.500000                    5.17520   
4              87.9           5.700000                    5.33593   
..              ...                ...                        ...   
87            155.6           3.566667                   22.23615   
88            157.4           3.533333                   21.03215   
89            159.0           3.533333                   20.11552   
90            160.6           3.666667                   19.13765   
91            162.1           3.800000                   18.51413   

    federal_debt_foreign_investors  federal_debt_private_investors_perc_gdp  
0                           1012.5                                 27.62881  
1                            983.3                                 25.68733  
2                            992.2                                 26.22848  
3                           1040.1                                 26.44819  
4                           1057.2                                 26.42185  
..                             ...                                      ...  
87                          7197.8                                 71.13901  
88                          

In [4]:
import pandas as pd
import numpy as np

# Replace placeholder missing values (e.g., '..') with np.nan
merged_1.replace({'..': np.nan}, inplace=True)

# Define a function to fill missing values with the mean of the previous two values
def fill_with_mean_of_previous_two(series):
    series = series.copy()  # Work on a copy to avoid inplace modifications
    for i in range(len(series)):
        if pd.isna(series[i]):
            if i >= 2:
                series[i] = (series[i - 1] + series[i - 2]) / 2
            elif i >= 1:  # If only one previous value exists
                series[i] = series[i - 1]
    return series

# Apply the function to numeric columns only
for col in merged_1.select_dtypes(include=['float64', 'int64']).columns:
    merged_1[col] = fill_with_mean_of_previous_two(merged_1[col])

# Save the updated DataFrame
merged_1.to_csv("../US_Datasets/merged_us.csv", index=False)


In [5]:
import pandas as pd
import numpy as np

# Replace placeholder missing values (e.g., NaN or '..') with np.nan if not already done
merged_1.replace({'..': np.nan}, inplace=True)

# Fill missing values in `gov_effectiveness_perc_rank` and `political_stability_perc_rank`
first_gov_effectiveness = merged_1['gov_effectiveness_perc_rank'].dropna().iloc[0]
first_political_stability = merged_1['political_stability_perc_rank'].dropna().iloc[0]

merged_1['gov_effectiveness_perc_rank'].fillna(first_gov_effectiveness, inplace=True)
merged_1['political_stability_perc_rank'].fillna(first_political_stability, inplace=True)

# Save the updated DataFrame if necessary
merged_1.to_csv("../US_Datasets/merged_us.csv", index=False)


/var/folders/wq/9scyb50x5_dd278dpcyf105m0000gn/T/ipykernel_11002/1688465007.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  merged_1['gov_effectiveness_perc_rank'].fillna(first_gov_effectiveness, inplace=True)
/var/folders/wq/9scyb50x5_dd278dpcyf105m0000gn/T/ipykernel_11002/1688465007.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate obj

In [6]:
merged_1

quarter  gdp_percentage_change_prev_q  fed_fund_rate  \
0   Q1-2001                           1.3       5.597000   
1   Q2-2001                           5.0       4.326703   
2   Q3-2001                           0.0       3.501522   
3   Q4-2001                           2.4       2.130435   
4   Q1-2002                           4.7       1.732889   
..      ...                           ...            ...   
87  Q4-2022                           7.2       3.653370   
88  Q1-2023                           6.6       4.514556   
89  Q2-2023                           4.3       4.988132   
90  Q3-2023                           7.7       5.259239   
91  Q4-2023                           4.8       5.330000   

    gov_effectiveness_perc_rank  PCECTPI  quarterly_fed_balance Bond Rating  \
0                     89.729729   75.012           -7483.666667          AA   
1                     89.729729   75.363           64579.666667           A   
2                     89.729729   75.401          -13889.666667           A   
3                     89.729729   75.432          -11785.333333           A   
4                     89.729729   75.584          -32188.333333           A   
..                          ...      ...                    ...         ...   
87                    87.264153  118.172         -140444.484514         BBB   
88                    87.735847  119.320         -226431.310502         BBB   
89                    87.735847  120.182          -97311.953949         AAA   
90                    87.735847  120.983         -100836.241845         AAA   
91                    87.735847  121.480         -169980.322779         AAA   

    political_stability_perc_rank  producer_price  tax_rev_perc_gdp  \
0                       53.968254      137.766667         11.857705   
1                       53.968254      136.233333         11.857705   
2                       53.968254      133.366667         11.857705   
3                       53.968254      129.400000         11.857705   
4                       53.968254      128.900000          9.868017   
..                            ...             ...               ...   
87                      46.226414      262.038333         12.054833   
88                      47.393364      258.652667         10.223807   
89                      47.393364      254.812667         10.223807   
90                      47.393364      256.816333         10.223807   
91                      47.393364      252.638000         10.223807   

    employment_cost  unemployment_rate  federal_debt_FED_perc_gdp  \
0              84.7           4.233333                    5.00371   
1              85.5           4.400000                    5.04859   
2              86.4           4.833333                    5.03962   
3              87.2           5.500000                    5.17520   
4              87.9           5.700000                    5.33593   
..              ...                ...                        ...   
87            155.6           3.566667                   22.23615   
88            157.4           3.533333                   21.03215   
89            159.0           3.533333                   20.11552   
90            160.6           3.666667                   19.13765   
91            162.1           3.800000                   18.51413   

    federal_debt_foreign_investors  federal_debt_private_investors_perc_gdp  
0                           1012.5                                 27.62881  
1                            983.3                                 25.68733  
2                            992.2                                 26.22848  
3                           1040.1                                 26.44819  
4                           1057.2                                 26.42185  
..                             ...                                      ...  
87                          7197.8                                 71.13901  
88                          

In [7]:
# lagging

# Identify columns to lag (all columns except 'Bond Rating' and 'quarter')
columns_to_lag = [col for col in merged_1.columns if col not in ['Bond Rating', 'quarter']]

# Create a new DataFrame to store the lagged features
lagged_df = merged_1[['quarter', 'Bond Rating']].copy()  # Keep 'quarter' and 'Bond Rating' in the new DataFrame

# Add lagged features to the new DataFrame
for col in columns_to_lag:
    lagged_df[f"{col}_lag1q"] = merged_1[col].shift(1)



In [8]:
lagged_df

quarter Bond Rating  gdp_percentage_change_prev_q_lag1q  \
0   Q1-2001          AA                                 NaN   
1   Q2-2001           A                                 1.3   
2   Q3-2001           A                                 5.0   
3   Q4-2001           A                                 0.0   
4   Q1-2002           A                                 2.4   
..      ...         ...                                 ...   
87  Q4-2022         BBB                                 7.4   
88  Q1-2023         BBB                                 7.2   
89  Q2-2023         AAA                                 6.6   
90  Q3-2023         AAA                                 4.3   
91  Q4-2023         AAA                                 7.7   

    fed_fund_rate_lag1q  gov_effectiveness_perc_rank_lag1q  PCECTPI_lag1q  \
0                   NaN                                NaN            NaN   
1              5.597000                          89.729729         75.012   
2              4.326703                          89.729729         75.363   
3              3.501522                          89.729729         75.401   
4              2.130435                          89.729729         75.432   
..                  ...                                ...            ...   
87             2.182935                          87.264153        117.014   
88             3.653370                          87.264153        118.172   
89             4.514556                          87.735847        119.320   
90             4.988132                          87.735847        120.182   
91             5.259239                          87.735847        120.983   

    quarterly_fed_balance_lag1q  political_stability_perc_rank_lag1q  \
0                           NaN                                  NaN   
1                  -7483.666667                            53.968254   
2                  64579.666667                            53.968254   
3                 -13889.666667                            53.968254   
4                 -11785.333333                            53.968254   
..                          ...                                  ...   
87               -286773.826654                            46.226414   
88               -140444.484514                            46.226414   
89               -226431.310502                            47.393364   
90                -97311.953949                            47.393364   
91               -100836.241845                            47.393364   

    producer_price_lag1q  tax_rev_perc_gdp_lag1q  employment_cost_lag1q  \
0                    NaN                     NaN                    NaN   
1             137.766667               11.857705                   84.7   
2             136.233333               11.857705                   85.5   
3             133.366667               11.857705                   86.4   
4             129.400000               11.857705                   87.2   
..                   ...                     ...                    ...   
87            269.906000               12.054833                  153.9   
88            262.038333               12.054833                  155.6   
89            258.652667               10.223807                  157.4   
90            254.812667               10.223807                  159.0   
91            256.816333               10.223807                  160.6   

    unemployment_rate_lag1q  federal_debt_FED_perc_gdp_lag1q  \
0                       NaN                              NaN   
1                  4.233333                          5.00371   
2                  4.400000                          5.04859   
3                  4.833333                          5.03962   
4                  5.500000                          5.17520   
..                      ...                              ...   
87                 3.533333                         23.20753   
88                 3.566667                 

In [9]:
import pandas as pd

# Encode 'Bond Rating' using the extended rating mapping
rating_mapping = {
    'AAA': 1, 'AA+': 2, 'AA': 3, 'AA-': 4,
    'A+': 5, 'A': 6, 'A-': 7,
    'BBB+': 8, 'BBB': 9, 'BBB-': 10,
    'BB+': 11, 'BB': 12, 'BB-': 13,
    'B+': 14, 'B': 15, 'B-': 16,
    'CCC+': 17, 'CCC': 18, 'CCC-': 19
}

# Map the 'Bond Rating' column to numeric values
lagged_df['Bond Rating Encoded'] = lagged_df['Bond Rating'].map(rating_mapping)

# Exclude non-numeric columns
numeric_columns = lagged_df.select_dtypes(include=['number'])

# Calculate the correlation matrix
correlation_matrix = numeric_columns.corr()

# Extract correlations of all features with the target ('Bond Rating Encoded'), excluding itself
correlation_with_target = correlation_matrix['Bond Rating Encoded'].drop('Bond Rating Encoded')

# Calculate absolute values and sort
absolute_correlation_with_target = correlation_with_target.abs().sort_values(ascending=False)

# Display the absolute correlations
print(absolute_correlation_with_target)


employment_cost_lag1q                            0.482350
federal_debt_FED_perc_gdp_lag1q                  0.473347
federal_debt_foreign_investors_lag1q             0.462730
federal_debt_private_investors_perc_gdp_lag1q    0.457069
PCECTPI_lag1q                                    0.453464
unemployment_rate_lag1q                          0.424389
gov_effectiveness_perc_rank_lag1q                0.360839
tax_rev_perc_gdp_lag1q                           0.305729
producer_price_lag1q                             0.262510
quarterly_fed_balance_lag1q                      0.216840
political_stability_perc_rank_lag1q              0.176993
fed_fund_rate_lag1q                              0.170191
gdp_percentage_change_prev_q_lag1q               0.044806
Name: Bond Rating Encoded, dtype: float64


In [10]:
lagged_df.tail()


quarter Bond Rating  gdp_percentage_change_prev_q_lag1q  \
87  Q4-2022         BBB                                 7.4   
88  Q1-2023         BBB                                 7.2   
89  Q2-2023         AAA                                 6.6   
90  Q3-2023         AAA                                 4.3   
91  Q4-2023         AAA                                 7.7   

    fed_fund_rate_lag1q  gov_effectiveness_perc_rank_lag1q  PCECTPI_lag1q  \
87             2.182935                          87.264153        117.014   
88             3.653370                          87.264153        118.172   
89             4.514556                          87.735847        119.320   
90             4.988132                          87.735847        120.182   
91             5.259239                          87.735847        120.983   

    quarterly_fed_balance_lag1q  political_stability_perc_rank_lag1q  \
87               -286773.826654                            46.226414   
88               -140444.484514                            46.226414   
89               -226431.310502                            47.393364   
90                -97311.953949                            47.393364   
91               -100836.241845                            47.393364   

    producer_price_lag1q  tax_rev_perc_gdp_lag1q  employment_cost_lag1q  \
87            269.906000               12.054833                  153.9   
88            262.038333               12.054833                  155.6   
89            258.652667               10.223807                  157.4   
90            254.812667               10.223807                  159.0   
91            256.816333               10.223807                  160.6   

    unemployment_rate_lag1q  federal_debt_FED_perc_gdp_lag1q  \
87                 3.533333                         23.20753   
88                 3.566667                         22.23615   
89                 3.533333                         21.03215   
90                 3.533333                         20.11552   
91                 3.666667                         19.13765   

    federal_debt_foreign_investors_lag1q  \
87                                7251.5   
88                                7197.8   
89                                7471.4   
90                                7559.0   
91                                7515.1   

    federal_debt_private_investors_perc_gdp_lag1q  Bond Rating Encoded  
87                                       71.04214                    9  
88                                       71.13901                    9  
89                                       71.46791                    1  
90                                       74.14416                    1  
91                                       76.43604                    1

In [13]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

# Assuming lagged_df is already loaded
data = lagged_df.copy()

# Encode bond ratings to numeric values
label_encoder = LabelEncoder()
data['Bond Rating Encoded'] = label_encoder.fit_transform(data['Bond Rating'])

# Shift target to predict the next quarter's bond rating
data['Bond Rating Target'] = data['Bond Rating Encoded'].shift(-1)

# Save Q4-2023 data separately for prediction
latest_data = data[data['quarter'] == 'Q4-2023']

# Drop rows where the target is NaN (only the last row is affected)
data = data[:-1]

# Define features and target
features = [
    'gdp_percentage_change_prev_q_lag1q',
    'fed_fund_rate_lag1q',
    'gov_effectiveness_perc_rank_lag1q',
    'PCECTPI_lag1q',
    'quarterly_fed_balance_lag1q',
    'political_stability_perc_rank_lag1q',
    'producer_price_lag1q',
    'tax_rev_perc_gdp_lag1q',
    'employment_cost_lag1q',
    'unemployment_rate_lag1q',
    'federal_debt_FED_perc_gdp_lag1q',
    'federal_debt_foreign_investors_lag1q',
    'federal_debt_private_investors_perc_gdp_lag1q'
]

# Handle missing values (forward fill and backward fill)
data.fillna(method='ffill', inplace=True)
data.fillna(method='bfill', inplace=True)

# Separate features (X) and target (y)
X = data[features]
y = data['Bond Rating Target']

# Split into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Train the model
model = RandomForestClassifier(random_state=42)
model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = model.predict(X_test_scaled)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# Predict bond rating for Q1 2024
if latest_data.empty:
    print("No data found for Q4-2023. Please verify the dataset.")
else:
    # Extract valid features
    X_latest = latest_data[features]

    # Scale and predict
    X_latest_scaled = scaler.transform(X_latest)
    y_next_quarter_pred = model.predict(X_latest_scaled)

    # Convert predictions to integers
    y_next_quarter_pred = y_next_quarter_pred.astype(int)

    # Verify predictions
    print("Predicted encoded value:", y_next_quarter_pred)
    print("Valid label encoder classes:", label_encoder.classes_)

    # Decode predictions
    predicted_bond_rating = label_encoder.inverse_transform(y_next_quarter_pred)
    print("Predicted Bond Rating for Q1 2024:", predicted_bond_rating[0])


Accuracy: 0.8947368421052632
Classification Report:
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         5
         1.0       1.00      1.00      1.00         1
         2.0       0.00      0.00      0.00         1
         3.0       0.50      1.00      0.67         1
         5.0       0.91      0.91      0.91        11

    accuracy                           0.89        19
   macro avg       0.68      0.78      0.72        19
weighted avg       0.87      0.89      0.88        19

Confusion Matrix:
 [[ 5  0  0  0  0]
 [ 0  1  0  0  0]
 [ 0  0  0  0  1]
 [ 0  0  0  1  0]
 [ 0  0  0  1 10]]
Predicted encoded value: [2]
Valid label encoder classes: ['A' 'AA' 'AAA' 'B' 'BB' 'BBB']
Predicted Bond Rating for Q1 2024: AAA


/var/folders/wq/9scyb50x5_dd278dpcyf105m0000gn/T/ipykernel_11002/3987050965.py:42: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
/var/folders/wq/9scyb50x5_dd278dpcyf105m0000gn/T/ipykernel_11002/3987050965.py:43: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)
/opt/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/opt/anaconda3/lib/python3.11/site-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being s